### PR TITLE
Makefile cuda samples

### PR DESCRIPTION
**Pull request by planetarymike**
Updated makefile to automatically download cuda_samples when compiling GPU code, as the samples are no longer shipped with CUDA

### CODE REVIEW

**Comment by planetarymike** [comment]
@bethangregory ,  can you confirm that this branch works on your machine?

**Comment by bethangregory** [comment]
Hi Mike,

The python route throws an error with this version. Changing line 52 in the makefile back to "CCOMP = g++-9" works. If having g++ only is important on your end, is there something else I can do to fix this?

Otherwise, everything works well.

Thanks!
Bethan

**Comment by planetarymike** [comment]
I think g++-9 is already included in these changes— could you double check the files on your machine after pulling this branch to make sure they’re the same as what’s shown in this pull request?

**Comment by bethangregory** [comment]
Oops sorry, I got mixed up. It needs to be g++ rather than g++-9 to work on mine.

**Comment by planetarymike** [comment]
OK--- g++-9 is needed for compatibility with the pipeline EMUS retrieval, so we need to get compilation with g++-9 working on you machine. Can you ensure gcc-9 is installed correctly with brew doctor and google the error you get? This is probably another Ventura / Xcode 15 specific problem, as the makefile works with no issues on my virtual machine running Moneterey / Xcode 13.

**Comment by planetarymike** [comment]
One thing you might try is downgrading xcode-select to version 14, since all of these new problems seem to have been introduced with Xcode 15

**Comment by planetarymike** [comment]
We could also standardize on g++-12 if that works on your machine. I don't have access to g++-13 on Ubuntu 22.04

**Comment by planetarymike** [comment]
@bethangregory , upon reflection it doesn't really matter what compiler we use to generate the python extension on each platform, so I added a line to switch to g++-13 in the makefile; see if this works for you.

**Comment by bethangregory** [comment]
This works!

**Comment by planetarymike** [comment]
Great, I'll merge

**Pull request merged**
